"""add_design_options_tables

Revision ID: 039251c0f3ee
Revises: c9d11aba4e23
Create Date: 2025-12-19 04:01:24.835177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039251c0f3ee'
down_revision: Union[str, Sequence[str], None] = 'c9d11aba4e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_design_options_id'), 'design_options', ['id'], unique=False)
    op.create_table('equipment_type_design_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=False),
    sa.Column('design_option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['design_option_id'], ['design_options.id'], ),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_type_id', 'design_option_id', name='uq_equip_type_design_option')
    )
    op.create_index(op.f('ix_equipment_type_design_options_id'), 'equipment_type_design_options', ['id'], unique=False)
    
    connection = op.get_bind()
    
    connection.execute(sa.text(
        "INSERT INTO design_options (id, name, description) VALUES (1, 'Handle Options', 'Equipment has handle location options')"
    ))
    connection.execute(sa.text(
        "INSERT INTO design_options (id, name, description) VALUES (2, 'Angle Options', 'Equipment has angle/curve type options')"
    ))
    
    equipment_types = connection.execute(sa.text("SELECT id, uses_handle_options, uses_angle_options FROM equipment_types")).fetchall()
    for eq_type in equipment_types:
        eq_id, uses_handle, uses_angle = eq_type
        if uses_handle:
            connection.execute(sa.text(
                f"INSERT INTO equipment_type_design_options (equipment_type_id, design_option_id) VALUES ({eq_id}, 1)"
            ))
        if uses_angle:
            connection.execute(sa.text(
                f"INSERT INTO equipment_type_design_options (equipment_type_id, design_option_id) VALUES ({eq_id}, 2)"
            ))
    
    op.drop_column('equipment_types', 'uses_handle_options')
    op.drop_column('equipment_types', 'uses_angle_options')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_types', sa.Column('uses_angle_options', sa.BOOLEAN(), nullable=True))
    op.add_column('equipment_types', sa.Column('uses_handle_options', sa.BOOLEAN(), nullable=True))
    op.drop_index(op.f('ix_equipment_type_design_options_id'), table_name='equipment_type_design_options')
    op.drop_table('equipment_type_design_options')
    op.drop_index(op.f('ix_design_options_id'), table_name='design_options')
    op.drop_table('design_options')
    # ### end Alembic commands ###
